export const NAVIGATE_SCREEN = 'NAVIGATE_SCREEN';
export const LISTING_DATA_SUCCESS = 'LISTING_DATA_SUCCESS';
export const LISTING_DATA_FAILURE = 'LISTING_DATA_FAILURE';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
